name = "aoc22_fortran"
version = "0.1.0"
license = "MIT"
author = "Carl Burkert"
copyright = "Copyright 2022, Carl Burkert"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
